version: '3.3'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/ssl:/etc/ssl"
      - "./www:/var/www/html"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./log/nginx:/var/log/nginx"
    ports:
      - "90:80"
      - "443:443"
    environment:
      - HOST=${HOST}
      - TZ=${TZ}
    depends_on:
      - phpfpm
      - mysqldb
      
  phpfpm:
    build: ./etc/php
    environment:
      - TZ=${TZ}
    volumes:
      - ./www/test-spa:/var/www/html/test-spa
      - ./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    ports:
      - "33066:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"


volumes:
  mysqldata: